---
gitlab_runner_container_id: 154
gitlab_runner_hostname: gitlab-runner
gitlab_runner_bridge: "{{ public_bridge }}"
gitlab_runner_ip_address: 172.16.10.154
gitlab_runner_ip_config: "{{ gitlab_runner_ip_address }}/{{ dmz_prefix }}"
gitlab_runner_gateway: "{{ dmz_gateway }}"
gitlab_runner_dns_servers:
  - 172.16.10.1
  - 1.1.1.1
gitlab_runner_root_password: "{{ vault_gitlab_runner_root_password }}"
gitlab_runner_coordinator_url: "https://gitlab.{{ public_domain }}"
gitlab_runner_registration_token: "{{ vault_gitlab_runner_registration_token }}"

# Runner configuration
gitlab_runner_executor: docker
gitlab_runner_concurrent: 4
gitlab_runner_tags:
  - docker
  - linux
  - self-hosted

# Docker executor configuration
gitlab_runner_docker_image: "debian:12"
gitlab_runner_docker_privileged: true
gitlab_runner_docker_volumes:
  - "/cache"
  - "/certs/client"
gitlab_runner_docker_pull_policy: "if-not-present"
