---
nextcloud_container_id: 155
nextcloud_hostname: nextcloud
nextcloud_bridge: "{{ public_bridge }}"
nextcloud_ip_address: 172.16.10.155
nextcloud_ip_config: "{{ nextcloud_ip_address }}/{{ dmz_prefix }}"
nextcloud_gateway: "{{ dmz_gateway }}"
nextcloud_dns_servers:
  - 172.16.10.1
  - 1.1.1.1
nextcloud_root_password: "{{ vault_nextcloud_root_password }}"
nextcloud_db_host: "172.16.10.50"
nextcloud_db_name: nextcloud
nextcloud_db_user: nextcloud
nextcloud_db_password: "{{ vault_nextcloud_db_password }}"
nextcloud_domain: "{{ public_domain }}"
nextcloud_trusted_domains:
  - "nextcloud.{{ public_domain }}"
  - "nextcloud.infra.local"

# Nextcloud SSO Configuration
nextcloud_sso_enabled: true
nextcloud_sso_provider: keycloak
nextcloud_sso_client_id: nextcloud
nextcloud_sso_client_secret: "{{ vault_nextcloud_oidc_client_secret | default('will_be_generated') }}"
nextcloud_sso_button_text: "Sign in with GitLab SSO"
nextcloud_sso_admin_email: "anders@viljo.se"
nextcloud_sso_admin_username: "anders"
