---
qbittorrent_container_id: 59
qbittorrent_hostname: qbittorrent
qbittorrent_domain: viljo.se
qbittorrent_memory: 2048
qbittorrent_cores: 2
qbittorrent_disk: 32
qbittorrent_swap: 512
qbittorrent_bridge: "{{ public_bridge | default('vmbr3') }}"
qbittorrent_ip_address: 172.16.10.59
qbittorrent_netmask: 24
qbittorrent_ip_config: "{{ qbittorrent_ip_address }}/{{ qbittorrent_netmask }}"
qbittorrent_vlan_tag: null
qbittorrent_gateway: 172.16.10.1
qbittorrent_dns_servers:
  - 172.16.10.1
  - 1.1.1.1
qbittorrent_rootfs_storage: local-lvm
qbittorrent_unprivileged: true
qbittorrent_start_onboot: true
qbittorrent_features:
  nesting: 1
qbittorrent_template_url: "{{ debian_template_url | default('http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst') }}"
qbittorrent_template_file: "{{ debian_template_file | default('/var/lib/vz/template/cache/debian-13-standard_13.1-2_amd64.tar.zst') }}"
qbittorrent_root_password: "{{ vault_qbittorrent_root_password | default('') }}"
qbittorrent_download_dir: /srv/downloads
qbittorrent_incomplete_dir: /srv/downloads/incomplete
qbittorrent_complete_dir: /srv/downloads/complete
qbittorrent_config_dir: /etc/qbittorrent
qbittorrent_web_port: 8080
qbittorrent_rootfs_path: "/var/lib/lxc/{{ qbittorrent_container_id }}/rootfs"
qbittorrent_external_domain: "{{ loopia_dns_domain | default(qbittorrent_domain) }}"
qbittorrent_service_port: 8080
qbittorrent_host_download_path: /srv/media/downloads
qbittorrent_categories: []
# Example category configuration:
# qbittorrent_categories:
#   - name: movies
#     save_path: /srv/downloads/complete/movies
#   - name: tv
#     save_path: /srv/downloads/complete/tv
