---
galaxy_info:
  author: DevOps Team
  description: Configure Nextcloud SSO via Keycloak OIDC (GitLab.com OAuth)
  company: Viljo Infrastructure
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - nextcloud
    - sso
    - oidc
    - keycloak
    - authentication
    - oauth

dependencies: []