http:
  middlewares:
    oauth2-proxy-auth:
      forwardAuth:
        address: "http://172.16.10.167:4180/oauth2/auth"
        trustForwardHeader: true
        authRequestHeaders:
          - X-Forwarded-Method
          - X-Forwarded-Proto
          - X-Forwarded-Host
          - X-Forwarded-Uri
          - X-Forwarded-For
        authResponseHeaders:
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - X-Auth-Request-Access-Token
          - Authorization
        authResponseHeadersRegex: "^X-"
