---
galaxy_info:
  author: Anders Viljo
  description: Configure GitLab SSO integration with Keycloak OIDC
  company: Viljo Infrastructure
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - gitlab
    - keycloak
    - oidc
    - sso
    - authentication

dependencies: []
